"""
Unit tests for SSBI Healthcare Multi-Agent System and Clinical RAG.
"""

import unittest
import os
import sys

# Ensure root directory is in pythonpath
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from agents.whatsapp_triage_agent import WhatsAppTriageAgent
from agents.patient_followup_agent import PatientFollowUpAgent, FollowUpState
from agents.clinical_rag_agent import ClinicalRAGAgent
from agents.multiagent_orchestrator import HealthcareMultiAgentOrchestrator


class TestHealthcareMultiAgentSystem(unittest.TestCase):

    def setUp(self):
        self.triage_agent = WhatsAppTriageAgent()
        self.followup_agent = PatientFollowUpAgent()
        self.rag_agent = ClinicalRAGAgent()
        self.orchestrator = HealthcareMultiAgentOrchestrator()

    def test_emergency_triage_classification(self):
        msg = "I am having sudden severe chest pain and cannot breathe"
        res = self.triage_agent.evaluate_triage(msg)
        self.assertEqual(res["triage_level"], "EMERGENCY")
        self.assertTrue(res["requires_physician_call"])
        self.assertIn("CRITICAL ALERT", res["reply_message"])

    def test_urgent_triage_classification(self):
        msg = "My child has a high fever and dizziness since morning"
        res = self.triage_agent.evaluate_triage(msg)
        self.assertEqual(res["triage_level"], "URGENT")
        self.assertTrue(res["requires_physician_call"])

    def test_routine_triage_classification(self):
        msg = "Hi, I would like to book an appointment next month for a dental checkup."
        res = self.triage_agent.evaluate_triage(msg)
        self.assertEqual(res["triage_level"], "ROUTINE")
        self.assertFalse(res["requires_physician_call"])

    def test_followup_state_machine_escalation(self):
        patient_id = "PT-1001"
        self.followup_agent.register_patient(patient_id, "Jane Doe", "Post-Op Appendectomy")

        self.assertEqual(self.followup_agent.patient_registry[patient_id]["state"], FollowUpState.SCHEDULED)

        msg = self.followup_agent.dispatch_scheduled_checkin(patient_id, current_day=3)
        self.assertIn("Jane Doe", msg)
        self.assertEqual(self.followup_agent.patient_registry[patient_id]["state"], FollowUpState.CHECKIN_SENT)

        resp = self.followup_agent.process_patient_reply(patient_id, "I have severe fever and increasing surgical pain")
        self.assertEqual(resp["patient_state"], FollowUpState.PHYSICIAN_ALERT_TRIGGERED)
        self.assertTrue(resp["alert_triggered"])
        self.assertIsNotNone(resp["physician_notification"])

    def test_clinical_rag_retrieval_grounded_answer(self):
        """On-topic query should retrieve the right disease and get a real,
        non-empty, disclaimer-bearing answer -- whether generated by the LLM
        (embedding-similarity path) or produced by the legacy keyword
        fallback if Ollama is unreachable in this environment."""
        query = "What are first-line recommendations for Type 2 Diabetes?"
        res = self.rag_agent.answer_query(query)

        self.assertEqual(res["matched_disease"], "Type 2 Diabetes Mellitus")
        self.assertTrue(res["response_text"].strip())
        self.assertGreater(len(res["response_text"]), 20)
        self.assertIn("Disclaimer", res["disclaimer"])

        if res.get("retrieval_method") == "embedding_similarity":
            # Real LLM-generated answer: should be topically grounded in the
            # retrieved diabetes protocol without hallucinating unrelated content.
            lowered = res["response_text"].lower()
            self.assertTrue(
                any(term in lowered for term in ["metformin", "diet", "exercise", "glycemic", "diabetes"]),
                f"Expected the grounded answer to reference the diabetes protocol, got: {res['response_text']}",
            )
        else:
            # Legacy fallback path was exercised (Ollama unreachable in this env).
            self.assertIn("Metformin", res["response_text"])

    def test_clinical_rag_hedges_on_low_relevance_query(self):
        """A query unrelated to anything in the knowledge base should not be
        force-matched to a disease -- it should hit the hedge/no-match path."""
        query = "Can I reschedule my routine dental cleaning next week?"
        res = self.rag_agent.answer_query(query)

        self.assertIsNone(res["matched_disease"])
        self.assertTrue(res["response_text"].strip())
        self.assertIn("Disclaimer", res["disclaimer"])
        # Response should hedge rather than confidently answering with clinical specifics.
        lowered = res["response_text"].lower()
        self.assertTrue(
            any(phrase in lowered for phrase in ["do not have", "consult", "healthcare provider", "physician"])
        )

    def test_orchestrator_routing(self):
        res1 = self.orchestrator.handle_incoming_message("PT-001", "I feel sudden numbness in left arm and chest pain")
        self.assertEqual(res1["routed_agent"], "WhatsAppTriageAgent")
        self.assertTrue(res1["alert"])

        res2 = self.orchestrator.handle_incoming_message("PT-002", "What are the common symptoms of Hypertension?")
        self.assertEqual(res2["routed_agent"], "ClinicalRAGAgent")
        self.assertFalse(res2["alert"])


if __name__ == "__main__":
    unittest.main()
